language: python

python:
  - 3.6

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

install:
  - pip install pipenv
  - pipenv install --dev --deploy

script:
  - pytest

branches:
  only:
  - gh-pages
  - /.*/
