language: python

python:
  - 3.6

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

install:
  - pip install -r requirements.txt
  - pip install flake8 flake8-comprehensions flake8-quotes flake8-builtins pytest

script:
  - pytest

branches:
  only:
  - gh-pages
  - /.*/
