language: python

python:
  - 2.7

install:
  - pip install -r requirements.txt
  - pip install flake8
  - pip install flake8-comprehensions
  - pip install flake8-quotes
  - pip install pytest

script:
  - pytest

branches:
  only:
  - gh-pages
  - /.*/
