language: python

python:
  - 2.7

install:
  - pip install -r requirements.txt
  - pip install flake8 flake8-comprehensions flake8-quotes flake8-builtins pytest

script:
  - pytest

branches:
  only:
  - gh-pages
  - /.*/
